# Generated by Django 3.2 on 2022-09-06 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_tg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True, verbose_name='ID пользователя телеграмм')),
                ('user_name', models.CharField(blank=True, max_length=2500, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь телеграмма',
                'verbose_name_plural': 'Пользователи телеграмма',
            },
        ),
        migrations.CreateModel(
            name='Request_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(verbose_name='Вопрос пользователя')),
                ('response', models.TextField(verbose_name='Ответ системы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user_tg', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос ответ',
                'verbose_name_plural': 'Запросы ответы',
            },
        ),
    ]
