# Generated by Django 4.1.1 on 2022-09-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_standard_messages"),
    ]

    operations = [
        migrations.RenameModel(old_name="User_tg", new_name="UserTg",),
    ]
