# Generated by Django 4.1.1 on 2022-09-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_rename_user_tg_usertg"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Request_response", new_name="RequestResponse",
        ),
        migrations.RenameModel(
            old_name="Standard_messages", new_name="StandardMessages",
        ),
    ]
