# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    env_file: [.env]
    volumes:
      - '.:/dp-agent'
  cobotqa:
    env_file: [.env]
    volumes:
      - './skills/CoBotQA:/src'
  alice:
    env_file: [.env]
    volumes:
      - './skills/ALICEChatAPI:/src'
  aiml:
    env_file: [.env]
    volumes: ['${EXTERNAL_FOLDER}/dp_logs:/logs', '${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov', '.:/dp-agent']
  rule_based_selector:
    env_file: [.env]
    volumes: ['${EXTERNAL_FOLDER}/dp_logs:/logs', '${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov', '.:/dp-agent']
  cobot_topics:
    env_file: [.env]
    volumes:
      - './annotators/CoBotTopicClassification:/src'
  cobot_sentiment:
    env_file: [.env]
    volumes:
      - './annotators/CoBotSentimentClassification:/src'
  sentseg:
    env_file: [.env]
    volumes:
      - './annotators/SentSeg:/src'
  cobot_offensiveness:
    env_file: [.env]
    volumes:
      - './annotators/CoBotOffensiveSpeechClassification:/src'
  cobot_dialogact:
    env_file: [.env]
    volumes:
      - './annotators/CoBotDialogActClassification:/src'
  transfertransfo:
    env_file: [.env]
    volumes:
      - './skills/transfertransfo:/app'
  program_y:
    env_file: [.env]
    volumes:
      - './skills/program-y:/src'
  convers_evaluation_selector:
    env_file: [.env]
    volumes:
      - './response_selectors/convers_evaluation_based_selector:/src'

version: '3.7'
