# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    command: sh -c 'bin/wait && gunicorn run_http:app_factory --bind 0.0.0.0:4242 --workers 4 --worker-class aiohttp.GunicornWebWorker'
    env_file: [.env.dev]
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  cobotqa:
    env_file: [.env.dev]
    volumes:
      - "./skills/CoBotQA:/src"
      - "./common:/src/common"
    ports:
      - 8001:8001
  cobot_topics:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotTopicClassification:/src"
    ports:
      - 8003:8003
  sentseg:
    env_file: [.env.dev]
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  sentrewrite:
    env_file: [.env.dev]
    volumes:
      - "./annotators/SentRewrite:/src"
    ports:
      - 8017:8017
  ner:
    env_file: [.env.dev]
    volumes:
      - './annotators/NER:/src'
    ports:
      - 8021:8021
  cobot_offensiveness:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotOffensiveSpeechClassification:/src"
    ports:
      - 8005:8005
  cobot_dialogact:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotDialogActClassification:/src"
    ports:
      - 8006:8006
  personality_catcher:
    env_file: [.env.dev]
    volumes:
      - "./skills/personality_catcher:/app"
    ports:
      - 8010:8010
  program_y:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y:/src"
      - "./skills/program-y/logs:/tmp"
      - "./common:/src/common"
    ports:
      - 8008:8008
  convers_evaluation_selector:
    env_file: [.env.dev]
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  mongo:
    env_file: [.env.dev]
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /data/db_new:/root/data/db
  toxic_classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovToxicClassification:/dp-agent/annotators/DeepPavlovToxicClassification"
    ports:
      - 8013:8013
  sentiment_classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovSentimentClassification:/dp-agent/annotators/DeepPavlovSentimentClassification"
    ports:
      - 8024:8024
  emotion_classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovEmotionClassification:/dp-agent/annotators/DeepPavlovEmotionClassification"
    ports:
      - 8038:8038
  intent_responder:
    env_file: [.env.dev]
    volumes:
      - "./skills/IntentResponder:/src"
    ports:
      - 8012:8012
  intent_catcher:
    env_file: [.env.dev]
    volumes:
      - "./annotators/IntentCatcher/src:/src"
    ports:
      - 8014:8014
  blacklisted_words:
    env_file: [.env.dev]
    volumes:
      - "./annotators/BlacklistedWordsDetector:/src"
    ports:
      - 8018:8018
  program_y_dangerous:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y-dangerous:/src"
      - "./skills/program-y-dangerous/logs:/tmp"
    ports:
      - 8022:8022
  cobot_nounphrases:
    env_file: [.env.dev]
    volumes:
      - "./annotators/nounphrases:/src"
    ports:
      - 8016:8016
  movie_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/movie_skill/src:/src"
    ports:
      - 8023:8023
  alice:
    env_file: [.env.dev]
    volumes:
      - "./skills/ALICEChatAPI:/src"
    ports:
      - 8000:8000
  eliza:
    env_file: [.env.dev]
    volumes:
      - "./skills/eliza:/src"
    ports:
      - 8047:8047
  emotion_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/emotion_skill:/src"
      - "./common:/src/common"
    ports:
      - 8049:8049
  tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/tfidf_retrieval:/src"
    ports:
      - 8028:8028
  book_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8039:8039
  entertainment_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8040:8040
  fashion_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8041:8041
  movie_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8042:8042
  music_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8034:8034
  politics_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8043:8043
  science_technology_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8044:8044
  sport_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8045:8045
  animals_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8050:8050
  topicalchat_convert_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_convert_retrieval:/src"
    ports:
      - 8060:8060
  convert_reddit:
    env_file: [.env.dev]
    volumes:
      - "./skills/convert_reddit:/app"
    ports:
      - 8029:8029
  personal_info_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/personal_info_skill:/src"
      - "./common:/src/common"
    ports:
      - 8030:8030
  asr:
    env_file: [.env.dev]
    volumes:
      - "./annotators/asr:/src"
    ports:
      - 8031:8031
  book_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/book_skill:/src"
      - "./common:/src/common"
    ports:
      - 8032:8032
  misheard_asr:
    env_file: [.env.dev]
    volumes:
      - "./skills/misheard_asr:/src"
    ports:
      - 8033:8033
  reddit_ner_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/reddit_ner_skill:/src"
      - "./common:/src/common"
    ports:
      - 8035:8035
  christmas_new_year_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/christmas_new_year_skill:/src"
    ports:
      - 8036:8036
  superbowl_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/superbowl_skill:/src"
    ports:
      - 8051:8051
  oscar_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/oscar_skill:/src"
    ports:
      - 8055:8055
  valentines_day_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/valentines_day_skill:/src"
    ports:
      - 8058:8058
  weather_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/weather_skill:/src"
    ports:
      - 8037:8037
  dummy_skill_dialog:
    env_file: [.env.dev]
    volumes:
      - "./skills/dummy_skill_dialog:/app"
    ports:
      - 8052:8052
  comet_atomic:
    env_file: [.env.dev]
    ports:
      - 8053:8053
  comet_conceptnet:
    env_file: [.env.dev]
    ports:
      - 8065:8065
  meta_script_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/meta_script_skill:/src"
      - "./common:/src/common"
    ports:
      - 8054:8054
  stop_detect:
    env_file: [.env.dev]
    volumes:
      - "./annotators/stop_detect:/src"
      - "./common:/src/common"
    ports:
      - 8056:8056
  cobot_convers_evaluator_annotator:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotConversationEvaluator:/src"
    ports:
      - 8063:8063
  coronavirus_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/coronavirus_skill:/src"
      - "./common:/src/common"
    ports:
      - 8061:8061
  small_talk_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/small_talk_skill:/src"
      - "./common:/src/common"
    ports:
      - 8062:8062
  program_y_wide:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y-wide:/src"
      - "./skills/program-y-wide/logs:/tmp"
    ports:
      - 8064:8064
  news_api_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/news_api_skill:/src"
      - "./common:/src/common"
    ports:
      - 8066:8066
version: "3.7"
