# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    env_file: [.env.dev]
    volumes:
      - ".:/dp-agent"
  cobotqa:
    env_file: [.env.dev]
    volumes:
      - "./skills/CoBotQA:/src"
    ports:
      - 8001:8001
  rule_based_selector:
    env_file: [.env.dev]
    volumes:
      - "./skill_selectors/rule_based_selector:/src"
    ports:
      - 8002:8002
  cobot_topics:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotTopicClassification:/src"
    ports:
      - 8003:8003
  sentseg:
    env_file: [.env.dev]
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  sentrewrite:
    env_file: [.env.dev]
    volumes:
      - "./annotators/SentRewrite:/src"
    ports:
      - 8017:8017
  ner:
    env_file: [.env.dev]
    volumes:
      - './annotators/NER:/src'
    ports:
      - 8021:8021
  cobot_offensiveness:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotOffensiveSpeechClassification:/src"
    ports:
      - 8005:8005
  cobot_dialogact:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotDialogActClassification:/src"
    ports:
      - 8006:8006
  transfertransfo:
    build:
      args:
        MODE: dev
    env_file: [.env.dev]
    volumes:
      - "./skills/transfertransfo:/app"
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8007 --timeout 60 --reload
    ports:
      - 8007:8007
  retrieval_chitchat:
    env_file: [.env.dev]
    volumes:
      - "./skills/retrieval_chitchat:/app"
    ports:
      - 8015:8015
  personality_catcher:
    env_file: [.env.dev]
    volumes:
      - "./skills/personality_catcher:/app"
    ports:
      - 8010:8010
  program_y:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y:/src"
      - "./skills/program-y/logs:/tmp"
    ports:
      - 8008:8008
  convers_evaluation_selector:
    env_file: [.env.dev]
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
    ports:
      - 8009:8009
  mongo:
    env_file: [.env.dev]
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /data/db_new:/root/data/db
  toxic_classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovToxicClassification:/src"
    ports:
      - 8013:8013
  intent_responder:
    env_file: [.env.dev]
    volumes:
      - "./skills/IntentResponder:/src"
    ports:
      - 8012:8012
  intent_catcher:
    env_file: [.env.dev]
    volumes:
      - "./annotators/IntentCatcher:/src"
    ports:
      - 8014:8014
  blacklisted_words:
    env_file: [.env.dev]
    volumes:
      - "./annotators/BlacklistedWordsDetector:/src"
    ports:
      - 8018:8018
  dummy_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/dummy_skill:/src"
    ports:
      - 8019:8019
  program_y_dangerous:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y-dangerous:/src"
      - "./skills/program-y-dangerous/logs:/tmp"
    ports:
      - 8022:8022
  cobot_nounphrases:
    env_file: [.env.dev]
    volumes:
      - "./annotators/nounphrases:/src"
    ports:
      - 8016:8016
version: "3.7"
