# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run -ch http_client --cors'
    env_file: [.env.dev]
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  cobotqa:
    env_file: [.env.dev]
    volumes:
      - "./skills/CoBotQA:/src"
      - "./common:/src/common"
    ports:
      - 8081:8081
  cobot-topics:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotTopicClassification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8001:8000
  cobot-dialogact:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotDialogActClassification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8002:8002
  cobot-convers-evaluator-annotator:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotConversationEvaluator:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8004:8004
  cobot-nounphrases:
    env_file: [.env.dev]
    volumes:
      - "./annotators/cobot_nounphrases:/src"
    ports:
      - 8006:8006
  program-y:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y:/src"
      - "./skills/program-y/logs:/tmp"
      - "./common:/src/common"
    ports:
      - 8008:8008
  personality-catcher:
    env_file: [.env.dev]
    volumes:
      - "./skills/personality_catcher:/app"
    ports:
      - 8010:8010
  sentseg:
    env_file: [.env.dev]
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  convers-evaluation-selector:
    env_file: [.env.dev]
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  sentrewrite:
    env_file: [.env.dev]
    volumes:
      - "./annotators/SentRewrite:/src"
    ports:
      - 8017:8017
  intent-responder:
    env_file: [.env.dev]
    volumes:
      - "./skills/IntentResponder:/src"
      - "./common:/src/common"
    ports:
      - 8012:8012
  intent-catcher:
    env_file: [.env.dev]
    volumes:
      - "./annotators/IntentCatcher/src:/src"
      - "./common:/src/common"
    ports:
      - 8014:8014
  blacklisted-words:
    env_file: [.env.dev]
    volumes:
      - "./annotators/BlacklistedWordsDetector:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  program-y-dangerous:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y-dangerous:/src"
      - "./skills/program-y-dangerous/logs:/tmp"
      - "./common:/src/common"
    ports:
      - 8022:8022
  movie-skill:
    env_file: [.env.dev]
    volumes:
      - "./common:/src/common"
      - "./skills/movie_skill:/src"
      - "./skills/CoBotQA:/src/CoBotQA"
    ports:
      - 8023:8023
  ner:
    env_file: [.env.dev]
    volumes:
      - './annotators/NER:/src'
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8021:8021
  alice:
    env_file: [.env.dev]
    volumes:
      - "./skills/ALICEChatAPI:/src"
    ports:
      - 8000:8000
  eliza:
    env_file: [.env.dev]
    volumes:
      - "./skills/eliza:/src"
    ports:
      - 8047:8047
  book-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8039:8039
  entertainment-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8040:8040
  fashion-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8041:8041
  movie-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8042:8042
  music-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8034:8034
  politics-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8043:8043
  science-technology-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8044:8044
  sport-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8045:8045
  animals-tfidf-retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8050:8050
  convert-reddit:
    env_file: [.env.dev]
    volumes:
      - "./skills/convert_reddit:/app"
      - "./common:/src/common"
    ports:
      - 8029:8029
  personal-info-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/personal_info_skill:/src"
      - "./common:/src/common"
    ports:
      - 8030:8030
  asr:
    env_file: [.env.dev]
    volumes:
      - "./annotators/asr:/src"
      - "./common:/src/common"
    ports:
      - 8031:8031
  misheard-asr:
    env_file: [.env.dev]
    volumes:
      - "./skills/misheard_asr:/src"
    ports:
      - 8033:8033
  book-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/book_skill:/src"
      - "./common:/src/common"
    ports:
      - 8032:8032
  christmas-new-year-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/christmas_new_year_skill:/src"
    ports:
      - 8036:8036
  superbowl-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/superbowl_skill:/src"
    ports:
      - 8051:8051
  oscar-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/oscar_skill:/src"
    ports:
      - 8055:8055
  valentines-day-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/valentines_day_skill:/src"
    ports:
      - 8058:8058
  weather-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/weather_skill:/src"
      - "./common:/src/common"
    ports:
      - 8037:8037
  emotion-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/emotion_skill:/src"
      - "./common:/src/common"
    ports:
      - 8049:8049
  dummy-skill-dialog:
    env_file: [.env.dev]
    volumes:
      - "./skills/dummy_skill_dialog:/app"
    ports:
      - 8052:8052
  comet-atomic:
    env_file: [.env.dev]
    ports:
      - 8053:8053
  comet-conceptnet:
    env_file: [.env.dev]
    ports:
      - 8065:8065
  meta-script-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/meta_script_skill:/src"
      - "./common:/src/common"
    ports:
      - 8054:8054
  short-story-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/short_story_skill:/src"
      - "./common:/src/common"
    ports:
      - 8057:8057
  coronavirus-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/coronavirus_skill:/src"
      - "./common:/src/common"
    ports:
      - 8061:8061
  small-talk-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/small_talk_skill:/src"
      - "./common:/src/common"
    ports:
      - 8062:8062
  game-cooperative-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/game_cooperative_skill:/src"
      - "./common:/src/common"
    ports:
      - 8068:8068
  program-y-wide:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y-wide:/src"
      - "./skills/program-y-wide/logs:/tmp"
    ports:
      - 8064:8064
  news-api-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/news_api_skill:/src"
      - "./common:/src/common"
    ports:
      - 8066:8066
  greeting-skill:
    env_file: [.env.dev]
    volumes:
      - "./common:/src/common"
      - "./skills/greeting_skill:/src"
    ports:
      - 8070:8070
  factoid-qa:
    env_file: [.env.dev]
    volumes:
      - "./skills/factoid_qa:/src"
      - "./common:/src/common"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8071:8071
  kbqa:
    env_file: [.env.dev]
    volumes:
      - "./annotators/kbqa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8072:8072
  entity-linking:
    env_file: [.env.dev]
    volumes:
      - "./annotators/entity_linking:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8075:8075
  wiki-parser:
    env_file: [.env.dev]
    volumes:
      - "./annotators/wiki_parser:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8077:8077
  factoid-classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovFactoidClassification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8073:8073
  mongo:
    env_file: [.env.dev]
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  spelling-preprocessing:
    env_file: [.env.dev]
    volumes:
      - "./annotators/spelling_preprocessing:/src"
    ports:
      - 8074:8074
  grounding-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/grounding_skill:/src"
      - "./common:/src/common"
    ports:
      - 8080:8080
  odqa:
    env_file: [.env.dev]
    volumes:
      - "./annotators/odqa:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8078:8078
  wikidata-dial-skill:
    env_file: [ .env.dev ]
    volumes:
      - "./skills/wikidata_dial_skill:/src"
    ports:
      - 8091:8091
  wikidata-dial-service:
    env_file: [ .env.dev ]
    volumes:
      - "./services/wikidata_dial_service:/src"
    ports:
      - 8092:8092
  question-generator:
    env_file: [.env.dev]
    volumes:
      - "./services/question_generator:/src"
    ports:
      - 8079:8079
  knowledge-grounding:
    env_file: [.env.dev]
    volumes:
      - "./services/knowledge_grounding:/src"
    ports:
      - 8083:8083
  dialog-breakdown:
    env_file: [.env.dev]
    volumes:
      - "./annotators/dialog_breakdown:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8082:8082
  knowledge-grounding-skill:
    env_file: [.env.dev]
    volumes:
      - "./common:/src/common"
      - "./skills/knowledge_grounding_skill:/src"
    ports:
      - 8085:8085
  friendship-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/friendship_skill:/src"
      - "./skills/meta_script_skill:/src/meta_script_skill"
      - "./common:/src/common"
    ports:
      - 8086:8086
  masked-lm:
    env_file: [.env.dev]
    volumes:
      - "./services/masked_lm:/src"
    ports:
      - 8088:8088
  entity-storer:
    env_file: [.env.dev]
    volumes:
      - "./common:/src/common"
      - "./annotators/entity_storer:/src"
    ports:
      - 8089:8089
  combined-classification:
    env_file: [.env.dev]
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
    ports:
      - 8087:8087
  dff-travel-skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/dff_travel_skill:/src"
      - "./common:/src/common"
      - "./skills/CoBotQA:/src/CoBotQA"
    ports:
      - 8096:8096

version: "3.7"
