# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    command: sh -c 'bin/wait && python3 run.py -ch http_client -rl -d -pl alexa_pipeline_conf.json -db db_conf.json'
    env_file: [.env.dev]
    volumes:
      - ".:/dp-agent"
  cobotqa:
    env_file: [.env.dev]
    volumes:
      - "./skills/CoBotQA:/src"
    ports:
      - 8001:8001
  cobot_topics:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotTopicClassification:/src"
    ports:
      - 8003:8003
  sentseg:
    env_file: [.env.dev]
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  sentrewrite:
    env_file: [.env.dev]
    volumes:
      - "./annotators/SentRewrite:/src"
    ports:
      - 8017:8017
  ner:
    env_file: [.env.dev]
    volumes:
      - './annotators/NER:/src'
    ports:
      - 8021:8021
  cobot_offensiveness:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotOffensiveSpeechClassification:/src"
    ports:
      - 8005:8005
  cobot_dialogact:
    env_file: [.env.dev]
    volumes:
      - "./annotators/CoBotDialogActClassification:/src"
    ports:
      - 8006:8006
  personality_catcher:
    env_file: [.env.dev]
    volumes:
      - "./skills/personality_catcher:/app"
    ports:
      - 8010:8010
  program_y:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y:/src"
      - "./skills/program-y/logs:/tmp"
    ports:
      - 8008:8008
  convers_evaluation_selector:
    env_file: [.env.dev]
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
    ports:
      - 8009:8009
  mongo:
    env_file: [.env.dev]
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /data/db_new:/root/data/db
  toxic_classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovToxicClassification:/dp-agent/annotators/DeepPavlovToxicClassification"
    ports:
      - 8013:8013
  sentiment_classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovSentimentClassification:/dp-agent/annotators/DeepPavlovSentimentClassification"
    ports:
      - 8024:8024
  emotion_classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovEmotionClassification:/dp-agent/annotators/DeepPavlovEmotionClassification"
    ports:
      - 8038:8038
  intent_responder:
    env_file: [.env.dev]
    volumes:
      - "./skills/IntentResponder:/src"
    ports:
      - 8012:8012
  intent_catcher:
    env_file: [.env.dev]
    volumes:
      - "./annotators/IntentCatcher/src:/src"
    ports:
      - 8014:8014
  blacklisted_words:
    env_file: [.env.dev]
    volumes:
      - "./annotators/BlacklistedWordsDetector:/src"
    ports:
      - 8018:8018
  dummy_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/dummy_skill:/src"
    ports:
      - 8019:8019
  program_y_dangerous:
    env_file: [.env.dev]
    volumes:
      - "./skills/program-y-dangerous:/src"
      - "./skills/program-y-dangerous/logs:/tmp"
    ports:
      - 8022:8022
  cobot_nounphrases:
    env_file: [.env.dev]
    volumes:
      - "./annotators/nounphrases:/src"
    ports:
      - 8016:8016
  movie_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/movie_skill/src:/src"
    ports:
      - 8023:8023
  attitude_classification:
    env_file: [.env.dev]
    volumes:
      - "./annotators/DeepPavlovAttitudeClassification:/dp-agent/annotators/DeepPavlovAttitudeClassification"
    ports:
      - 8025:8025
  alice:
    env_file: [.env.dev]
    volumes:
      - "./skills/ALICEChatAPI:/src"
    ports:
      - 8000:8000
  eliza:
    env_file: [.env.dev]
    volumes:
      - "./skills/eliza:/src"
    ports:
      - 8047:8047
  emotion_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/emotion_skill:/src"
    ports:
      - 8049:8049
  news_skill:
    env_file: [.env.dev]
    volumes:
      - "./common:/src/common"
      - "./skills/alexa-prize-news/src:/src/src"
      - "./skills/alexa-prize-news/server.py:/src/src/server.py"
      - "./skills/alexa-prize-news/updater.py:/src/src/updater.py"
    ports:
      - 8027:8027
  tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/tfidf_retrieval:/src"
    ports:
      - 8028:8028
  book_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8039:8039
  entertainment_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8040:8040
  fashion_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8041:8041
  movie_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8042:8042
  music_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8034:8034
  politics_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8043:8043
  science_technology_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8044:8044
  sport_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8045:8045
  animals_tfidf_retrieval:
    env_file: [.env.dev]
    volumes:
      - "./skills/topicalchat_tfidf_retrieval:/src"
    ports:
      - 8050:8050
  convert_reddit:
    env_file: [.env.dev]
    volumes:
      - "./skills/convert_reddit:/app"
    ports:
      - 8029:8029
  convert_reddit_with_personality:
    env_file: [.env.dev]
    volumes:
      - "./skills/convert_reddit_with_personality:/app"
    ports:
      - 8048:8048
  personal_info_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/personal_info_skill:/src"
      - "./common:/src/common"
    ports:
      - 8030:8030
  asr:
    env_file: [.env.dev]
    volumes:
      - "./annotators/asr:/src"
    ports:
      - 8031:8031
  book_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/book_skill:/src"
    ports:
      - 8032:8032
  misheard_asr:
    env_file: [.env.dev]
    volumes:
      - "./skills/misheard_asr:/src"
    ports:
      - 8033:8033
  christmas_new_year_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/christmas_new_year_skill:/src"
    ports:
      - 8036:8036
  superbowl_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/superbowl_skill:/src"
    ports:
      - 8051:8051
  weather_skill:
    env_file: [.env.dev]
    volumes:
      - "./skills/weather_skill:/src"
    ports:
      - 8037:8037
version: "3.7"
