services:
  agent:
    build: {context: ./, dockerfile: dockerfile_agent}
    container_name: agent
    depends_on: [mongo]
    ports: ['28888:8888']
    tty: true
    volumes: ['.:/dp-agent']
  mongo:
    command: mongod
    image: mongo:3.2.0
    ports: ['27017:27017']
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
version: '3'
