services:
  agent:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run -ch http_client --cors'
    build:
      context: ./
      dockerfile: dockerfile_agent
    environment:
      WAIT_HOSTS: "cobot_topics:8001, cobot_dialogact_topics:8002, cobot_dialogact_intents:8003,
        cobot_nounphrases:8006, program_y:8008, sentseg:8011, convers_evaluation_selector:8009, personality_catcher:8010,
        intent_responder:8012, intent_catcher:8014, blacklisted_words:8018,
        toxic_classification:8013, sentrewrite:8017, ner:8021,  program_y_dangerous:8022, movie_skill:8023,
        sentiment_classification:8024,
        convert_reddit:8029, personal_info_skill:8030, asr:8031, book_skill:8032, misheard_asr:8033,
        christmas_new_year_skill:8036, weather_skill:8037, emotion_classification:8038, alice:8000,
        eliza:8047, emotion_skill:8049, dummy_skill_dialog:8052, comet_atomic:8053, meta_script_skill:8054,
        oscar_skill:8055, coronavirus_skill:8061, small_talk_skill:8062, game_cooperative_skill:8068, program_y_wide:8064,
        comet_conceptnet:8065, news_api_skill:8066, short_story_skill:8057, greeting_skill:8070, factoid_qa:8071, kbqa:8072,
        factoid_classification:8073, spelling_preprocessing:8074"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-480}

  cobot_topics:
    build:
      args:
        skill_endpoint: cobot_topics
        skillconfig: annotators/cobot_topics/cobot_bert.json
        skillhost: 0.0.0.0
        skillport: 8001
        skilldir: annotators/cobot_topics/
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  cobot_dialogact_topics:
    build:
      args:
        skill_endpoint: cobot_dialogact_topics
        skillconfig: annotators/cobot_dialogact_topics/cobot_bert.json
        skillhost: 0.0.0.0
        skillport: 8002
        skilldir: annotators/cobot_dialogact_topics/
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  cobot_dialogact_intents:
    build:
      args:
        skill_endpoint: cobot_dialogact_intents
        skillconfig: annotators/cobot_dialogact_intents/cobot_bert.json
        skillhost: 0.0.0.0
        skillport: 8003
        skilldir: annotators/cobot_dialogact_intents/
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  cobot_convers_evaluator_annotator:
    build:
      args:
        skill_endpoint: model
        skillconfig: annotators/cobot_convers_evaluator_annotator/cobot_conveval_bert.json
        skillhost: 0.0.0.0
        skillport: 8004
        skilldir: annotators/cobot_convers_evaluator_annotator
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  cobot_nounphrases:
    build:
      context: ./annotators/cobot_nounphrases/
    command: bash -c "gunicorn --workers=1 server:app -b 0.0.0.0:8006 -t 60"

  program_y:
    build:
      context: .
      dockerfile: ./skills/program-y/Dockerfile

  personality_catcher:
    build:
      context: ./skills/personality_catcher/
    command: uvicorn server:app --host 0.0.0.0 --port 8010
    volumes: []

  sentseg:
    build:
      context: ./annotators/SentSeg/
    command: bash -c "./setup.sh && gunicorn --workers=1 server:app -b 0.0.0.0:8011 -t 100"
    volumes: []

  convers_evaluation_selector:
    build:
      context: .
      dockerfile: ./response_selectors/convers_evaluation_based_selector/Dockerfile
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8009 -t 15
    volumes: []

  toxic_classification:
    build:
      args:
        skill_endpoint: toxicity_annotations
        skillconfig: annotators/DeepPavlovToxicClassification/toxic_classification.json
        skillhost: 0.0.0.0
        skillport: 8013
        skilldir: annotators/DeepPavlovToxicClassification/
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  sentiment_classification:
    build:
      args:
        skill_endpoint: sentiment_annotations
        skillconfig: annotators/DeepPavlovSentimentClassification/sentiment_sst_conv_bert.json
        skillhost: 0.0.0.0
        skillport: 8024
        skilldir: annotators/DeepPavlovSentimentClassification/
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  sentrewrite:
    build:
      context: ./annotators/SentRewrite/
    command: bash -c "./setup.sh && gunicorn --workers=1 server:app -b 0.0.0.0:8017 -t 60"

  intent_responder:
    build:
      context: ./skills/IntentResponder/
    command: gunicorn --workers=1 --name=responder --bind 0.0.0.0:8012 --timeout=100 server:app
    volumes: []

  intent_catcher:
    build:
      context: ./annotators/IntentCatcher/
    command: gunicorn --workers=1 --name=catcher --bind 0.0.0.0:8014 --timeout=100 server:app
    volumes: []

  blacklisted_words:
    build:
      context: ./annotators/BlacklistedWordsDetector/
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8018

  program_y_dangerous:
    build:
      context: ./skills/program-y-dangerous/

  movie_skill:
    build:
      context: .
      dockerfile: ./skills/movie_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8023 --timeout=300 --preload
    volumes: []

  ner:
    build:
      context: ./annotators/NER/
    environment:
      DEVICE: cuda
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8021 -t 100
    volumes: []
    tty: true

  alice:
    build:
      context: ./skills/ALICEChatAPI/
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8000

  eliza:
    build:
      context: ./skills/eliza/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8047
    volumes: []

  book_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_book_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: book
        CONFIDENCE_THRESHOLD: 0.51
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8039
    volumes: []

  entertainment_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_entertainment_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: entertainment
        CONFIDENCE_THRESHOLD: 0.59
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8040
    volumes: []

  fashion_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_fashion_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: fashion
        CONFIDENCE_THRESHOLD: 0.6
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8041
    volumes: []

  movie_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_movie_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: movie
        CONFIDENCE_THRESHOLD: 0.6
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8042
    volumes: []

  music_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_music_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: music
        CONFIDENCE_THRESHOLD: 0.6
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8034
    volumes: []

  politics_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_politics_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: politics
        CONFIDENCE_THRESHOLD: 0.6
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8043
    volumes: []

  science_technology_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_science_technology_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: science_technology
        CONFIDENCE_THRESHOLD: 0.6
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8044
    volumes: []

  sport_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_sport_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: sport
        CONFIDENCE_THRESHOLD: 0.6
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8045
    volumes: []

  animals_tfidf_retrieval:
    build:
      context: ./skills/topicalchat_tfidf_retrieval/
      args:
        TOPICAL_DATA_URL: http://lnsigo.mipt.ru/export/alexaprize_data/topicalchat_tfidf_retrieval/topicalchat_animals_data.tar.gz
        MODELS_URL: http://lnsigo.mipt.ru/export/models/new_vectorizer_2.zip
        TOPIC_NAME: animals
        CONFIDENCE_THRESHOLD: 0.6
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8050
    volumes: []

  convert_reddit:
    build:
      context: ./skills/convert_reddit/
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8029 -t 60
    volumes: []

  personal_info_skill:
    build:
      context: .
      dockerfile: ./skills/personal_info_skill/Dockerfile
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8030
    volumes: []

  asr:
    build:
      context: .
      dockerfile: ./annotators/asr/Dockerfile
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8031

  misheard_asr:
    build:
      context: ./skills/misheard_asr/
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8033

  book_skill:
    build:
      context: .
      dockerfile: ./skills/book_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8032

  christmas_new_year_skill:
    build:
      context: ./skills/christmas_new_year_skill/
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8036
    volumes: []

  superbowl_skill:
    build:
      context: ./skills/superbowl_skill/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8051
    volumes: []

  oscar_skill:
    build:
      context: ./skills/oscar_skill/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8055
    volumes: []

  valentines_day_skill:
    build:
      context: ./skills/valentines_day_skill/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8058
    volumes: []

  weather_skill:
    build:
            context: .
            dockerfile: ./skills/weather_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8037
    volumes: []

  emotion_skill:
    build:
      context: .
      dockerfile: ./skills/emotion_skill/Dockerfile
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8049
    volumes: []

  emotion_classification:
    build:
      args:
        skill_endpoint: emotion_annotations
        skillconfig: annotators/DeepPavlovEmotionClassification/emo_bert.json
        skillhost: 0.0.0.0
        skillport: 8038
        skilldir: annotators/DeepPavlovEmotionClassification/
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  dummy_skill_dialog:
    build:
      context: ./skills/dummy_skill_dialog/
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8052

  comet_atomic:
    build:
      context: ./annotators/COMeT/
      args:
        GRAPH: atomic
        PRETRAINED_MODEL: http://lnsigo.mipt.ru/export/alexaprize_data/comet/atomic_pretrained_model.pickle
        PREPROCESS_DATA: http://lnsigo.mipt.ru/export/alexaprize_data/comet/categories_oEffect%%23oReact%%23oWant%%23xAttr%%23xEffect%%23xIntent%%23xNeed%%23xReact%%23xWant-maxe1_17-maxe2_35-maxr_1.pickle
        TEST_SCRIPT: test_atomic.py
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8053
    volumes: []
    environment:
      - CUDA_VISIBLE_DEVICES=0

  comet_conceptnet:
    build:
      context: ./annotators/COMeT/
      args:
        GRAPH: conceptnet
        PRETRAINED_MODEL: http://lnsigo.mipt.ru/export/alexaprize_data/conceptnet/conceptnet_pretrained_model.pickle
        PREPROCESS_DATA: http://lnsigo.mipt.ru/export/alexaprize_data/conceptnet/rel_language-trainsize_100-devversion_12-maxe1_10-maxe2_15-maxr_5.pickle
        TEST_SCRIPT: test_conceptnet.py
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8065
    volumes: []
    environment:
      - CUDA_VISIBLE_DEVICES=0

  meta_script_skill:
    build:
      context: .
      dockerfile: skills/meta_script_skill/Dockerfile
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8054
    volumes: []

  short_story_skill:
    build:
      context: .
      dockerfile: ./skills/short_story_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8057
  stop_detect:
    build:
      args:
        skill_endpoint: model
        skillconfig: annotators/stop_detect/stop_detect.json
        skillhost: 0.0.0.0
        skillport: 8056
        skilldir: annotators/stop_detect
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  coronavirus_skill:
    build:
      context: .
      dockerfile: ./skills/coronavirus_skill/Dockerfile
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8061
    volumes: []

  small_talk_skill:
    build:
      context: .
      dockerfile: ./skills/small_talk_skill/Dockerfile
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8062
    volumes: []

  game_cooperative_skill:
    build:
      args:
        SERVICE_PORT: 8068
      context: .
      dockerfile: ./skills/game_cooperative_skill/Dockerfile
    command: bash server_run.sh "gunicorn --workers=2 server:app -b 0.0.0.0:8068 --reload"
    volumes: []

  program_y_wide:
    build:
      context: ./skills/program-y-wide/
    working_dir: /src/dream_aiml/scripts/xnix
    command: ./sanic.sh

  news_api_skill:
    build:
      context: .
      dockerfile: ./skills/news_api_skill/Dockerfile
    environment:
      - ASYNC_SIZE=3
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8066 -t 15
    volumes: []

  greeting_skill:
    build:
      context: .
      dockerfile: ./skills/greeting_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8070 --timeout=60 --preload
    volumes: []

  factoid_qa:
    build:
      context: .
      dockerfile: ./skills/factoid_qa/Dockerfile
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8071
    volumes: []

  kbqa:
    build:
      args:
        skill_endpoint: answers
        skillconfig: annotators/kbqa/kbqa_cq.json
        skillhost: 0.0.0.0
        skillport: 8072
        skilldir: annotators/kbqa/
      context: ./
      dockerfile: annotators/kbqa/Dockerfile
    environment:
      - CUDA_VISIBLE_DEVICES=0

  factoid_classification:
    build:
      args:
        skill_endpoint: factoid_annotations
        skillconfig: annotators/DeepPavlovFactoidClassification/factoid_classification.json
        skillhost: 0.0.0.0
        skillport: 8073
        skilldir: annotators/DeepPavlovFactoidClassification/
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0

  spelling_preprocessing:
    build:
      context: ./annotators/spelling_preprocessing/
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8074 --timeout=100
    volumes: []

version: '3.7'
