services:
  agent:
    command: sh -c 'bin/wait && python3 -m core.run -ch http_client'
    build:
      context: ./
      dockerfile: dockerfile_agent
    ports:
      - 4242:4242
    environment:
      WAIT_HOSTS: rule_based_selector:8002, cobotqa:8001, cobot_topics:8003, transfertransfo:8007, toxic_classification:8013
      WAIT_HOSTS_TIMEOUT: 120
  rule_based_selector:
    build:
      args:
        skill_endpoint: selected_skills
        skillconfig: skill_selectors/alexa_skill_selectors/rule_based_selector.json
        skillhost: 0.0.0.0
        skillport: 8002
      context: ./
      dockerfile: dp/dockerfile_skill_cpu
    environment:
      - CUDA_VISIBLE_DEVICES=""
  cobotqa:
    build:
      context: ./skills/CoBotQA/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8001
    volumes: []
  cobot_topics:
    build:
      context: ./annotators/CoBotTopicClassification/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8003
    volumes: []
  cobot_sentiment:
    build:
      context: ./annotators/CoBotSentimentClassification/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8004
    volumes: []
  cobot_offensiveness:
    build:
      context: ./annotators/CoBotOffensiveSpeechClassification/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8005
    volumes: []
  cobot_dialogact:
    build:
      context: ./annotators/CoBotDialogActClassification/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8006
    volumes: []
  transfertransfo:
    build:
      context: ./skills/transfertransfo/
    command: uvicorn server:app --host 0.0.0.0 --port 8007
    volumes: []
  program_y:
    build:
      context: ./skills/program-y/
    working_dir: /src/dream_aiml/scripts/xnix
    command: ./sanic.sh
  personality_catcher:
    build:
      context: ./skills/personality_catcher/
    command: uvicorn server:app --host 0.0.0.0 --port 8010
    volumes: []
  sentseg:
    build:
      context: ./annotators/SentSeg/
    command: bash -c "./setup.sh && gunicorn --workers=1 server:app -b 0.0.0.0:8011"
    volumes: []
  convers_evaluation_selector:
    build:
      context: ./response_selectors/convers_evaluation_based_selector/
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8009
    volumes: []
  toxic_classification:
    build:
      args:
        skill_endpoint: toxicity_annotations
        skillconfig: annotators/DeepPavlovToxicClassification/toxic_classification.json
        skillhost: 0.0.0.0
        skillport: 8013
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES="0"
version: '3.7'
