services:
  agent:
    build:
      context: ./
      dockerfile: dockerfile_agent
    container_name: agent
    depends_on:
      - aiml
      - mongo
    ports:
    - 4242:4242
    tty: true
  aiml:
    build:
      args:
        skill_endpoint: aiml
        skillconfig: skills/aiml/aiml_skill.json
        skillhost: 0.0.0.0
        skillport: 2080
      context: ./
      dockerfile: dp/dockerfile_skill_cpu
    container_name: aiml
    environment:
      - CUDA_VISIBLE_DEVICES=""
    ports:
      - 2080:2080
    tty: true
  mongo:
    command: mongod
    image: mongo:3.2.0
    ports:
      - 27017:27017
  rule_based_selector:
    container_name: rule_based_selector
    build:
      args:
        skill_endpoint: selected_skills
        skillconfig: skill_selectors/alexa_skill_selectors/rule_based_selector.json
        skillhost: 0.0.0.0
        skillport: 8002
      context: ./
      dockerfile: dp/dockerfile_skill_cpu
    environment:
      - CUDA_VISIBLE_DEVICES=""
    ports:
      - 8002:8002
    tty: true
  toxic_classification:
    container_name: toxic_classification
    build:
      args:
        skill_endpoint: toxicity_annotations
        skillconfig: annotators/DeepPavlovToxicClassification/toxic_classification.json
        skillhost: 0.0.0.0
        skillport: 8013
      context: ./
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES="0"
    ports:
      - 8013:8013
    tty: true
version: '3.7'
