services:
  alice:
    build:
      context: ./skills/ALICEChatAPI/
    ports: ['8000:8000']
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8000
    volumes: []
  cobotqa:
    build:
      context: ./skills/CoBotQA/
    ports: ['8001:8001']
    command: gunicorn --workers=2 server:app -b 0.0.0.0:8001
    volumes: []   
version: '3.7'
