services:
  agent:
    image: ${DOCKER_REGISTRY}/agent:${VERSION}
    env_file:
      - ${ENV_FILE}
    ports:
      - ${DP_AGENT_PORT}:4242
  cobotqa:
    image: ${DOCKER_REGISTRY}/cobotqa:${VERSION}
    env_file:
      - ${ENV_FILE}
  sentseg:
    image: ${DOCKER_REGISTRY}/sentseg:${VERSION}
    env_file:
      - ${ENV_FILE}
  cobot-topics:
     image: ${DOCKER_REGISTRY}/cobot-topics:${VERSION}
     env_file:
       - ${ENV_FILE}
  cobot-dialogact:
     image: ${DOCKER_REGISTRY}/cobot-dialogact:${VERSION}
     env_file:
       - ${ENV_FILE}
  cobot-convers-evaluator-annotator:
     image: ${DOCKER_REGISTRY}/cobot-convers-evaluator-annotator:${VERSION}
     env_file:
       - ${ENV_FILE}
  sentrewrite:
    image: ${DOCKER_REGISTRY}/sentrewrite:${VERSION}
    env_file:
      - ${ENV_FILE}
  convers-evaluation-selector:
    image: ${DOCKER_REGISTRY}/convers-evaluation-selector:${VERSION}
    env_file:
      - ${ENV_FILE}
  personality-catcher:
    image: ${DOCKER_REGISTRY}/personality-catcher:${VERSION}
    env_file:
      - ${ENV_FILE}
  program-y:
    image: ${DOCKER_REGISTRY}/program-y:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"lets chat\"]],\"user_ids\":[123131]}' http://localhost:8008/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  intent-catcher:
    image: ${DOCKER_REGISTRY}/intent-catcher:${VERSION}
    env_file:
      - ${ENV_FILE}
  intent-responder:
    image: ${DOCKER_REGISTRY}/intent-responder:${VERSION}
    env_file:
      - ${ENV_FILE}
  blacklisted-words:
    image: ${DOCKER_REGISTRY}/blacklisted-words:${VERSION}
    env_file:
      - ${ENV_FILE}
  program-y-dangerous:
    image: ${DOCKER_REGISTRY}/program-y-dangerous:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"i want to commit a suicide\"]],\"user_ids\":[123131]}' http://localhost:8022/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  ner:
    image: ${DOCKER_REGISTRY}/ner:${VERSION}
    env_file:
      - ${ENV_FILE}
  mongo:
    command: mongod
    image: mongo:4.0.0
    env_file:
      - ${ENV_FILE}
  movie-skill:
    image: ${DOCKER_REGISTRY}/movie-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  alice:
    image: ${DOCKER_REGISTRY}/alice:${VERSION}
    env_file:
      - ${ENV_FILE}
  eliza:
    image: ${DOCKER_REGISTRY}/eliza:${VERSION}
    env_file:
      - ${ENV_FILE}
  book-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/book-tfidf-retrieval:${VERSION}
  entertainment-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/entertainment-tfidf-retrieval:${VERSION}
  fashion-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/fashion-tfidf-retrieval:${VERSION}
  movie-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/movie-tfidf-retrieval:${VERSION}
  music-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/music-tfidf-retrieval:${VERSION}
  politics-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/politics-tfidf-retrieval:${VERSION}
  science-technology-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/science-technology-tfidf-retrieval:${VERSION}
  sport-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/sport-tfidf-retrieval:${VERSION}
  animals-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/animals-tfidf-retrieval:${VERSION}
  convert-reddit:
    image: ${DOCKER_REGISTRY}/convert-reddit:${VERSION}
    env_file:
      - ${ENV_FILE}
  personal-info-skill:
    image: ${DOCKER_REGISTRY}/personal-info-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  asr:
    image: ${DOCKER_REGISTRY}/asr:${VERSION}
    env_file:
      - ${ENV_FILE}
  misheard-asr:
    image: ${DOCKER_REGISTRY}/misheard-asr:${VERSION}
    env_file:
      - ${ENV_FILE}
  short-story-skill:
    image: ${DOCKER_REGISTRY}/short-story-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  book-skill:
    image: ${DOCKER_REGISTRY}/book-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  christmas-new-year-skill:
    image: ${DOCKER_REGISTRY}/christmas-new-year-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  superbowl-skill:
    image: ${DOCKER_REGISTRY}/superbowl-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  oscar-skill:
    image: ${DOCKER_REGISTRY}/oscar-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  valentines-day-skill:
    image: ${DOCKER_REGISTRY}/valentines-day-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  weather-skill:
    image: ${DOCKER_REGISTRY}/weather-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  emotion-skill:
    image: ${DOCKER_REGISTRY}/emotion-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  comet-atomic:
    image: ${DOCKER_REGISTRY}/comet-atomic:${VERSION}
    env_file:
      - ${ENV_FILE}
  comet-conceptnet:
    image: ${DOCKER_REGISTRY}/comet-conceptnet:${VERSION}
    env_file:
      - ${ENV_FILE}
  dummy-skill-dialog:
    image: ${DOCKER_REGISTRY}/dummy-skill-dialog:${VERSION}
    env_file:
      - ${ENV_FILE}
  meta-script-skill:
    image: ${DOCKER_REGISTRY}/meta-script-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  coronavirus-skill:
    image: ${DOCKER_REGISTRY}/coronavirus-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  small-talk-skill:
    image: ${DOCKER_REGISTRY}/small-talk-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  game-cooperative-skill:
    image: ${DOCKER_REGISTRY}/game-cooperative-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  kbqa:
    image: ${DOCKER_REGISTRY}/kbqa:${VERSION}
    env_file:
      - ${ENV_FILE}
  odqa:
    image: ${DOCKER_REGISTRY}/odqa:${VERSION}
    env_file:
      - ${ENV_FILE}
  program-y-wide:
    image: ${DOCKER_REGISTRY}/program-y-wide:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"lets chat\"]],\"user_ids\":[123131]}' http://localhost:8064/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  news-api-skill:
    image: ${DOCKER_REGISTRY}/news-api-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  greeting-skill:
    image: ${DOCKER_REGISTRY}/greeting-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  spelling-preprocessing:
    image: ${DOCKER_REGISTRY}/spelling-preprocessing:${VERSION}
    env_file:
      - ${ENV_FILE}
  wiki-parser:
    image: ${DOCKER_REGISTRY}/wiki-parser:${VERSION}
    env_file:
      - ${ENV_FILE}
  factoid-qa:
    image: ${DOCKER_REGISTRY}/factoid-qa:${VERSION}
    env_file:
      - ${ENV_FILE}
  factoid-classification:
    image: ${DOCKER_REGISTRY}/factoid-classification:${VERSION}
    env_file:
      - ${ENV_FILE}
  cobot-nounphrases:
    image: ${DOCKER_REGISTRY}/cobot-nounphrases:${VERSION}
    env_file:
      - ${ENV_FILE}
  entity-linking:
    image: ${DOCKER_REGISTRY}/entity-linking:${VERSION}
    env_file:
      - ${ENV_FILE}
  question-generator:
    image: ${DOCKER_REGISTRY}/question-generator:${VERSION}
    env_file:
      - ${ENV_FILE}
  grounding-skill:
    image: ${DOCKER_REGISTRY}/grounding-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  knowledge-grounding:
    image: ${DOCKER_REGISTRY}/knowledge-grounding:${VERSION}
    env_file:
      - ${ENV_FILE}
  dialog-breakdown:
    image: ${DOCKER_REGISTRY}/dialog-breakdown:${VERSION}
    env_file:
      - ${ENV_FILE}
  friendship-skill:
    image: ${DOCKER_REGISTRY}/friendship-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  masked-lm:
    image: ${DOCKER_REGISTRY}/masked-lm:${VERSION}
    env_file:
      - ${ENV_FILE}
  entity-storer:
    image: ${DOCKER_REGISTRY}/entity-storer:${VERSION}
    env_file:
      - ${ENV_FILE}
  knowledge-grounding-skill:
    image: ${DOCKER_REGISTRY}/knowledge-grounding-skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  combined-classification:
     image: ${DOCKER_REGISTRY}/combined-classification:${VERSION}
     env_file:
       - ${ENV_FILE}
  wikidata-dial-skill:
     image: ${DOCKER_REGISTRY}/wikidata-dial-skill:${VERSION}
     env_file:
       - ${ENV_FILE}
volumes:
  external-logs:
  external-deeppavlov:
version: '3.7'
