services:
  agent:
    image: ${DOCKER_REGISTRY}/agent:${VERSION}
    env_file:
      - ${ENV_FILE}
    ports:
      - ${DP_AGENT_PORT}:4242
  sentseg:
    image: ${DOCKER_REGISTRY}/sentseg:${VERSION}
    env_file:
      - ${ENV_FILE}
  cobot_intent_topics:
     image: ${DOCKER_REGISTRY}/cobot_intent_topics:${VERSION}
     env_file:
       - ${ENV_FILE}
  cobot_topics:
    image: ${DOCKER_REGISTRY}/cobot_intent_topics:${VERSION}
    env_file:
      - ${ENV_FILE}
  cobot_dialogact_topics:
    image: ${DOCKER_REGISTRY}/cobot_intent_topics:${VERSION}
    env_file:
      - ${ENV_FILE}
  cobot_dialogact_intents:
    image: ${DOCKER_REGISTRY}/cobot_intent_topics:${VERSION}
    env_file:
      - ${ENV_FILE}
  cobot_convers_evaluator_annotator:
     image: ${DOCKER_REGISTRY}/cobot_convers_evaluator_annotator:${VERSION}
     env_file:
       - ${ENV_FILE}
  sentrewrite:
    image: ${DOCKER_REGISTRY}/sentrewrite:${VERSION}
    env_file:
      - ${ENV_FILE}
  convers_evaluation_selector:
    image: ${DOCKER_REGISTRY}/convers_evaluation_selector:${VERSION}
    env_file:
      - ${ENV_FILE}
  personality_catcher:
    image: ${DOCKER_REGISTRY}/personality_catcher:${VERSION}
    env_file:
      - ${ENV_FILE}
  program_y:
    image: ${DOCKER_REGISTRY}/program_y:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"lets chat\"]],\"user_ids\":[123131]}' http://localhost:8008/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  toxic_classification:
    image: ${DOCKER_REGISTRY}/toxic_classification:${VERSION}
    env_file:
      - ${ENV_FILE}
  sentiment_classification:
    image: ${DOCKER_REGISTRY}/sentiment_classification:${VERSION}
    env_file:
      - ${ENV_FILE}
  intent_catcher:
    image: ${DOCKER_REGISTRY}/intent_catcher:${VERSION}
    env_file:
      - ${ENV_FILE}
  intent_responder:
    image: ${DOCKER_REGISTRY}/intent_responder:${VERSION}
    env_file:
      - ${ENV_FILE}
  blacklisted_words:
    image: ${DOCKER_REGISTRY}/blacklisted_words:${VERSION}
    env_file:
      - ${ENV_FILE}
  program_y_dangerous:
    image: ${DOCKER_REGISTRY}/program_y_dangerous:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"i want to commit a suicide\"]],\"user_ids\":[123131]}' http://localhost:8022/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  ner:
    image: ${DOCKER_REGISTRY}/ner:${VERSION}
    env_file:
      - ${ENV_FILE}
  mongo:
    command: mongod
    image: mongo:4.0.0
    env_file:
      - ${ENV_FILE}
  movie_skill:
    image: ${DOCKER_REGISTRY}/movie_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  alice:
    image: ${DOCKER_REGISTRY}/alice:${VERSION}
    env_file:
      - ${ENV_FILE}
  eliza:
    image: ${DOCKER_REGISTRY}/eliza:${VERSION}
    env_file:
      - ${ENV_FILE}
  book_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/book_tfidf_retrieval:${VERSION}
  entertainment_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/entertainment_tfidf_retrieval:${VERSION}
  fashion_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/fashion_tfidf_retrieval:${VERSION}
  movie_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/movie_tfidf_retrieval:${VERSION}
  music_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/music_tfidf_retrieval:${VERSION}
  politics_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/politics_tfidf_retrieval:${VERSION}
  science_technology_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/science_technology_tfidf_retrieval:${VERSION}
  sport_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/sport_tfidf_retrieval:${VERSION}
  animals_tfidf_retrieval:
    image: ${DOCKER_REGISTRY}/animals_tfidf_retrieval:${VERSION}
  convert_reddit:
    image: ${DOCKER_REGISTRY}/convert_reddit:${VERSION}
    env_file:
      - ${ENV_FILE}
  personal_info_skill:
    image: ${DOCKER_REGISTRY}/personal_info_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  asr:
    image: ${DOCKER_REGISTRY}/asr:${VERSION}
    env_file:
      - ${ENV_FILE}
  misheard_asr:
    image: ${DOCKER_REGISTRY}/misheard_asr:${VERSION}
    env_file:
      - ${ENV_FILE}
  short_story_skill:
    image: ${DOCKER_REGISTRY}/short_story_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  book_skill:
    image: ${DOCKER_REGISTRY}/book_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  christmas_new_year_skill:
    image: ${DOCKER_REGISTRY}/christmas_new_year_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  superbowl_skill:
    image: ${DOCKER_REGISTRY}/superbowl_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  oscar_skill:
    image: ${DOCKER_REGISTRY}/oscar_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  valentines_day_skill:
    image: ${DOCKER_REGISTRY}/valentines_day_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  weather_skill:
    image: ${DOCKER_REGISTRY}/weather_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  emotion_classification:
    image: ${DOCKER_REGISTRY}/emotion_classification:${VERSION}
    env_file:
      - ${ENV_FILE}
  emotion_skill:
    image: ${DOCKER_REGISTRY}/emotion_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  comet_atomic:
    image: ${DOCKER_REGISTRY}/comet_atomic:${VERSION}
    env_file:
      - ${ENV_FILE}
  comet_conceptnet:
    image: ${DOCKER_REGISTRY}/comet_conceptnet:${VERSION}
    env_file:
      - ${ENV_FILE}
  dummy_skill_dialog:
    image: ${DOCKER_REGISTRY}/dummy_skill_dialog:${VERSION}
    env_file:
      - ${ENV_FILE}
  meta_script_skill:
    image: ${DOCKER_REGISTRY}/meta_script_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  stop_detect:
    image: ${DOCKER_REGISTRY}/stop_detect:${VERSION}
    env_file:
      - ${ENV_FILE}
  coronavirus_skill:
    image: ${DOCKER_REGISTRY}/coronavirus_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  small_talk_skill:
    image: ${DOCKER_REGISTRY}/small_talk_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  game_cooperative_skill:
    image: ${DOCKER_REGISTRY}/game_cooperative_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  kbqa:
    image: ${DOCKER_REGISTRY}/kbqa:${VERSION}
    env_file:
      - ${ENV_FILE}
  program_y_wide:
    image: ${DOCKER_REGISTRY}/program_y_wide:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"lets chat\"]],\"user_ids\":[123131]}' http://localhost:8064/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  news_api_skill:
    image: ${DOCKER_REGISTRY}/news_api_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  greeting_skill:
    image: ${DOCKER_REGISTRY}/greeting_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  spelling_preprocessing:
    image: ${DOCKER_REGISTRY}/spelling_preprocessing:${VERSION}
    env_file:
      - ${ENV_FILE}
volumes:
  external-logs:
  external-deeppavlov:
version: '3.7'
