services:
  agent:
    image: 127.0.0.1:5000/agent:latest
    env_file: [.env.staging]
  cobotqa:
    image: 127.0.0.1:5000/cobotqa:latest
    env_file: [.env.staging]
  alice:
    image: 127.0.0.1:5000/alice:latest
    env_file: [.env.staging]
  aiml:
    image: 127.0.0.1:5000/aiml:latest
    volumes: ['external-logs:/logs', 'external-deeppavlov:/root/.deeppavlov']
    env_file: [.env.staging]
  rule_based_selector:
    image: 127.0.0.1:5000/rule_based_selector:latest
    volumes: ['external-logs:/logs', 'external-deeppavlov:/root/.deeppavlov']
    env_file: [.env.staging]
  cobot_topics:
    image: 127.0.0.1:5000/cobot_topics:latest
    env_file: [.env.staging]
  cobot_sentiment:
    image: 127.0.0.1:5000/cobot_sentiment:latest
    env_file: [.env.staging]
  cobot_offensiveness:
    image: 127.0.0.1:5000/cobot_offensiveness:latest
    env_file: [.env.staging]
  cobot_dialogact:
    image: 127.0.0.1:5000/cobot_dialogact:latest
    env_file: [.env.staging]
  transfertransfo:
    image: 127.0.0.1:5000/transfertransfo:latest
    env_file: [.env.staging]
  convers_evaluation_selector:
    image: 127.0.0.1:5000/convers_evaluation_selector:latest
    env_file: [.env.staging]
volumes:
  external-logs:
  external-deeppavlov:
version: '3.7'
