services:
  agent:
    image: ${DOCKER_REGISTRY}/agent
    env_file: [.env.staging]
  cobotqa:
    image: ${DOCKER_REGISTRY}/cobotqa
    env_file: [.env.staging]
  rule_based_selector:
    image: ${DOCKER_REGISTRY}/rule_based_selector
    env_file: [.env.staging]
  cobot_topics:
    image: ${DOCKER_REGISTRY}/cobot_topics
    env_file: [.env.staging]
  cobot_sentiment:
    image: ${DOCKER_REGISTRY}/cobot_sentiment
    env_file: [.env.staging]
  sentseg:
    image: ${DOCKER_REGISTRY}/sentseg
    env_file: [.env.staging]
  sentrewrite:
    image: ${DOCKER_REGISTRY}/sentrewrite
    env_file: [.env.staging]
  cobot_offensiveness:
    image: ${DOCKER_REGISTRY}/cobot_offensiveness
    env_file: [.env.staging]
  cobot_dialogact:
    image: ${DOCKER_REGISTRY}/cobot_dialogact
    env_file: [.env.staging]
  transfertransfo:
    image: ${DOCKER_REGISTRY}/transfertransfo
    env_file: [.env.staging]
  retrieval_chitchat:
    image: ${DOCKER_REGISTRY}/retrieval_chitchat
    env_file: [.env.staging]
  convers_evaluation_selector:
    image: ${DOCKER_REGISTRY}/convers_evaluation_selector
    env_file: [.env.staging]
  personality_catcher:
    image: ${DOCKER_REGISTRY}/personality_catcher
    env_file: [.env.staging]
  program_y:
    image: ${DOCKER_REGISTRY}/program_y
    env_file: [.env.staging]
  toxic_classification:
    image: ${DOCKER_REGISTRY}/toxic_classification
    env_file: [.env.staging]
  intent_catcher:
    image: ${DOCKER_REGISTRY}/intent_catcher
    env_file: [.env.staging]
  intent_responder:
    image: ${DOCKER_REGISTRY}/intent_responder
    env_file: [.env.staging]
  blacklisted_words:
    image: ${DOCKER_REGISTRY}/blacklisted_words
    env_file: [.env.staging]
  dummy_skill:
    image: ${DOCKER_REGISTRY}/dummy_skill
    env_file: [.env.staging]
  program_y_dangerous:
    image: ${DOCKER_REGISTRY}/program_y_dangerous
    env_file: [.env.staging]
volumes:
  external-logs:
  external-deeppavlov:
version: '3.7'
