services:
  agent:
    image: ${DOCKER_REGISTRY}/agent:${VERSION}
    env_file:
      - ${ENV_FILE}
    ports:
      - ${DP_AGENT_PORT}:4242
  cobotqa:
    image: ${DOCKER_REGISTRY}/cobotqa:${VERSION}
    env_file:
      - ${ENV_FILE}
  sentseg:
    image: ${DOCKER_REGISTRY}/sentseg:${VERSION}
    env_file:
      - ${ENV_FILE}
  cobot-topics:
     image: ${DOCKER_REGISTRY}/cobot_topics:${VERSION}
     env_file:
       - ${ENV_FILE}
  cobot-dialogact-intents:
     image: ${DOCKER_REGISTRY}/cobot_dialogact_intents:${VERSION}
     env_file:
       - ${ENV_FILE}
  cobot-dialogact-topics:
     image: ${DOCKER_REGISTRY}/cobot_dialogact_topics:${VERSION}
     env_file:
       - ${ENV_FILE}
  cobot-convers-evaluator-annotator:
     image: ${DOCKER_REGISTRY}/cobot_convers_evaluator_annotator:${VERSION}
     env_file:
       - ${ENV_FILE}
  sentrewrite:
    image: ${DOCKER_REGISTRY}/sentrewrite:${VERSION}
    env_file:
      - ${ENV_FILE}
  convers-evaluation-selector:
    image: ${DOCKER_REGISTRY}/convers_evaluation_selector:${VERSION}
    env_file:
      - ${ENV_FILE}
  personality-catcher:
    image: ${DOCKER_REGISTRY}/personality_catcher:${VERSION}
    env_file:
      - ${ENV_FILE}
  program-y:
    image: ${DOCKER_REGISTRY}/program_y:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"lets chat\"]],\"user_ids\":[123131]}' http://localhost:8008/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  toxic-classification:
    image: ${DOCKER_REGISTRY}/toxic_classification:${VERSION}
    env_file:
      - ${ENV_FILE}
  sentiment-classification:
    image: ${DOCKER_REGISTRY}/sentiment_classification:${VERSION}
    env_file:
      - ${ENV_FILE}
  intent-catcher:
    image: ${DOCKER_REGISTRY}/intent_catcher:${VERSION}
    env_file:
      - ${ENV_FILE}
  intent-responder:
    image: ${DOCKER_REGISTRY}/intent_responder:${VERSION}
    env_file:
      - ${ENV_FILE}
  blacklisted-words:
    image: ${DOCKER_REGISTRY}/blacklisted_words:${VERSION}
    env_file:
      - ${ENV_FILE}
  program-y-dangerous:
    image: ${DOCKER_REGISTRY}/program_y_dangerous:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"i want to commit a suicide\"]],\"user_ids\":[123131]}' http://localhost:8022/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  ner:
    image: ${DOCKER_REGISTRY}/ner:${VERSION}
    env_file:
      - ${ENV_FILE}
  mongo:
    command: mongod
    image: mongo:4.0.0
    env_file:
      - ${ENV_FILE}
  movie-skill:
    image: ${DOCKER_REGISTRY}/movie_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  alice:
    image: ${DOCKER_REGISTRY}/alice:${VERSION}
    env_file:
      - ${ENV_FILE}
  eliza:
    image: ${DOCKER_REGISTRY}/eliza:${VERSION}
    env_file:
      - ${ENV_FILE}
  book-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/book_tfidf_retrieval:${VERSION}
  entertainment-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/entertainment_tfidf_retrieval:${VERSION}
  fashion-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/fashion_tfidf_retrieval:${VERSION}
  movie-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/movie_tfidf_retrieval:${VERSION}
  music-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/music_tfidf_retrieval:${VERSION}
  politics-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/politics_tfidf_retrieval:${VERSION}
  science-technology-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/science_technology_tfidf_retrieval:${VERSION}
  sport-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/sport_tfidf_retrieval:${VERSION}
  animals-tfidf-retrieval:
    image: ${DOCKER_REGISTRY}/animals_tfidf_retrieval:${VERSION}
  convert-reddit:
    image: ${DOCKER_REGISTRY}/convert_reddit:${VERSION}
    env_file:
      - ${ENV_FILE}
  personal-info-skill:
    image: ${DOCKER_REGISTRY}/personal_info_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  asr:
    image: ${DOCKER_REGISTRY}/asr:${VERSION}
    env_file:
      - ${ENV_FILE}
  misheard-asr:
    image: ${DOCKER_REGISTRY}/misheard_asr:${VERSION}
    env_file:
      - ${ENV_FILE}
  short-story-skill:
    image: ${DOCKER_REGISTRY}/short_story_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  book-skill:
    image: ${DOCKER_REGISTRY}/book_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  christmas-new-year-skill:
    image: ${DOCKER_REGISTRY}/christmas_new_year_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  superbowl-skill:
    image: ${DOCKER_REGISTRY}/superbowl_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  oscar-skill:
    image: ${DOCKER_REGISTRY}/oscar_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  valentines-day-skill:
    image: ${DOCKER_REGISTRY}/valentines_day_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  weather-skill:
    image: ${DOCKER_REGISTRY}/weather_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  emotion-classification:
    image: ${DOCKER_REGISTRY}/emotion_classification:${VERSION}
    env_file:
      - ${ENV_FILE}
  emotion-skill:
    image: ${DOCKER_REGISTRY}/emotion_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  comet-atomic:
    image: ${DOCKER_REGISTRY}/comet_atomic:${VERSION}
    env_file:
      - ${ENV_FILE}
  comet-conceptnet:
    image: ${DOCKER_REGISTRY}/comet_conceptnet:${VERSION}
    env_file:
      - ${ENV_FILE}
  dummy-skill-dialog:
    image: ${DOCKER_REGISTRY}/dummy_skill_dialog:${VERSION}
    env_file:
      - ${ENV_FILE}
  meta-script-skill:
    image: ${DOCKER_REGISTRY}/meta_script_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  stop-detect:
    image: ${DOCKER_REGISTRY}/stop_detect:${VERSION}
    env_file:
      - ${ENV_FILE}
  coronavirus-skill:
    image: ${DOCKER_REGISTRY}/coronavirus_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  small-talk-skill:
    image: ${DOCKER_REGISTRY}/small_talk_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  game-cooperative-skill:
    image: ${DOCKER_REGISTRY}/game_cooperative_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  kbqa:
    image: ${DOCKER_REGISTRY}/kbqa:${VERSION}
    env_file:
      - ${ENV_FILE}
  program-y-wide:
    image: ${DOCKER_REGISTRY}/program_y_wide:${VERSION}
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --header \"Content-Type: application/json\" --request POST --data '{\"sentences_batch\":[[\"lets chat\"]],\"user_ids\":[123131]}' http://localhost:8064/api/rest/v1.0/ask || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 1m
  news-api-skill:
    image: ${DOCKER_REGISTRY}/news_api_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  greeting-skill:
    image: ${DOCKER_REGISTRY}/greeting_skill:${VERSION}
    env_file:
      - ${ENV_FILE}
  spelling-preprocessing:
    image: ${DOCKER_REGISTRY}/spelling_preprocessing:${VERSION}
    env_file:
      - ${ENV_FILE}
  wiki-parser:
    image: ${DOCKER_REGISTRY}/wiki_parser:${VERSION}
    env_file:
      - ${ENV_FILE}
  factoid-qa:
    image: ${DOCKER_REGISTRY}/factoid_qa:${VERSION}
    env_file:
      - ${ENV_FILE}
  factoid-classification:
    image: ${DOCKER_REGISTRY}/factoid_classification:${VERSION}
    env_file:
      - ${ENV_FILE}
  cobot-nounphrases:
    image: ${DOCKER_REGISTRY}/cobot_nounphrases:${VERSION}
    env_file:
      - ${ENV_FILE}
  entity-linking:
    image: ${DOCKER_REGISTRY}/entity_linking:${VERSION}
    env_file:
      - ${ENV_FILE}
  question-generator:
    image: ${DOCKER_REGISTRY}/question_generator:${VERSION}
    env_file:
      - ${ENV_FILE}
volumes:
  external-logs:
  external-deeppavlov:
version: '3.7'
