services:
  agent:
    env_file: [ .env.dev ]
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
      - ".:/dp-agent"
    ports:
      - 4242:4242
  kbqa:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=9
  factoid-classification:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=9
  odqa:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=6
  comet-atomic:
    env_file: [ .env.dev ]
    environment:
      - CUDA_VISIBLE_DEVICES=6
  comet-conceptnet:
    env_file: [ .env.dev ]
    environment:
      - CUDA_VISIBLE_DEVICES=6
  knowledge-grounding:
    env_file: [ .env.dev ]
    environment:
      - CUDA_VISIBLE_DEVICES=8
  dialog-breakdown:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=5
  combined-classification:
    env_file: [ .env.dev ]
    environment:
      - CUDA_VISIBLE_DEVICES=7
  mongo:
    env_file: [ .env.dev ]
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  cobotqa:
    env_file: [ .env.dev ]
  cobot-convers-evaluator-annotator:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  cobot-nounphrases:
    env_file: [ .env.dev ]
  cobot-topics:
    env_file: [ .env.dev ]
  cobot-dialogact:
    env_file: [ .env.dev ]
  program-y:
    env_file: [ .env.dev ]
  personality-catcher:
    env_file: [ .env.dev ]
  sentseg:
    env_file: [ .env.dev ]
  convers-evaluation-selector:
    env_file: [ .env.dev ]
  sentrewrite:
    env_file: [ .env.dev ]
  intent-responder:
    env_file: [ .env.dev ]
  intent-catcher:
    env_file: [ .env.dev ]
  blacklisted-words:
    env_file: [ .env.dev ]
  program-y-dangerous:
    env_file: [ .env.dev ]
  movie-skill:
    env_file: [ .env.dev ]
  ner:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  alice:
    env_file: [ .env.dev ]
  eliza:
    env_file: [ .env.dev ]
  book-tfidf-retrieval:
    env_file: [ .env.dev ]
  entertainment-tfidf-retrieval:
    env_file: [ .env.dev ]
  fashion-tfidf-retrieval:
    env_file: [ .env.dev ]
  movie-tfidf-retrieval:
    env_file: [ .env.dev ]
  music-tfidf-retrieval:
    env_file: [ .env.dev ]
  politics-tfidf-retrieval:
    env_file: [ .env.dev ]
  science-technology-tfidf-retrieval:
    env_file: [ .env.dev ]
  sport-tfidf-retrieval:
    env_file: [ .env.dev ]
  animals-tfidf-retrieval:
    env_file: [ .env.dev ]
  convert-reddit:
    env_file: [ .env.dev ]
  personal-info-skill:
    env_file: [ .env.dev ]
  asr:
    env_file: [ .env.dev ]
  misheard-asr:
    env_file: [ .env.dev ]
  book-skill:
    env_file: [ .env.dev ]
  christmas-new-year-skill:
    env_file: [ .env.dev ]
  superbowl-skill:
    env_file: [ .env.dev ]
  oscar-skill:
    env_file: [ .env.dev ]
  valentines-day-skill:
    env_file: [ .env.dev ]
  weather-skill:
    env_file: [ .env.dev ]
  emotion-skill:
    env_file: [ .env.dev ]
  dummy-skill-dialog:
    env_file: [ .env.dev ]
  meta-script-skill:
    env_file: [ .env.dev ]
  short-story-skill:
    env_file: [ .env.dev ]
  coronavirus-skill:
    env_file: [ .env.dev ]
  small-talk-skill:
    env_file: [ .env.dev ]
  game-cooperative-skill:
    env_file: [ .env.dev ]
  program-y-wide:
    env_file: [ .env.dev ]
  news-api-skill:
    env_file: [ .env.dev ]
  greeting-skill:
    env_file: [ .env.dev ]
  factoid-qa:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  entity-linking:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  wiki-parser:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  spelling-preprocessing:
    env_file: [ .env.dev ]
  grounding-skill:
    env_file: [ .env.dev ]
  masked-lm:
    env_file: [ .env.dev ]
    environment:
      - CUDA_VISIBLE_DEVICES=9
  dff-friendship-skill:
    env_file: [ .env.dev ]
  entity-storer:
    env_file: [ .env.dev ]
  knowledge-grounding-skill:
    env_file: [ .env.dev ]
  wikidata-dial-skill:
    env_file: [ .env.dev ]
  wikidata-dial-service:
    env_file: [ .env.dev ]
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  dff-animals-skill:
    env_file: [ .env.dev ]
  dff-travel-skill:
    env_file: [ .env.dev ]
  dff-food-skill:
    env_file: [ .env.dev ]
version: '3.7'
