services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
  toxic-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  sentiment-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  emotion-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  question-generator:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  kbqa:
    environment:
      - CUDA_VISIBLE_DEVICES=9
  factoid-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=9
  odqa:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  comet-atomic:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  comet-conceptnet:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  knowledge-grounding:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  wiki-parser:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=10.11.1.1:8077
      - PORT=8077
version: '3.7'
