services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
  cobot_topics:
    environment:
      - CUDA_VISIBLE_DEVICES=5
  cobot_dialogact_topics:
    environment:
      - CUDA_VISIBLE_DEVICES=5
  cobot_dialogact_intents:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  cobot_convers_evaluator_annotator:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  toxic_classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  sentiment_classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  emotion_classification:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  stop_detect:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  kbqa:
    environment:
      - CUDA_VISIBLE_DEVICES=9
  factoid_classification:
    environment:
      - CUDA_VISIBLE_DEVICES=9
  wiki_parser:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=10.11.1.1:9077
      - PORT=8077
version: '3.7'
