services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
  cobot-topics:
    environment:
      - CUDA_VISIBLE_DEVICES=5
  cobot-dialogact-topics:
    environment:
      - CUDA_VISIBLE_DEVICES=5
  cobot-dialogact-intents:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  cobot-convers-evaluator-annotator:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  toxic-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  sentiment-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  emotion-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  stop-detect:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  kbqa:
    environment:
      - CUDA_VISIBLE_DEVICES=9
  factoid-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=9
  odqa:
    environment:
      - CUDA_VISIBLE_DEVICES=0
  wiki-parser:
    command: [ "nginx", "-g", "daemon off;" ]
    build:
      context: dp/proxy/
      dockerfile: Dockerfile
    environment:
      - PROXY_PASS=10.11.1.1:8077
      - PORT=8077
  comet-atomic:
    environment:
      - CUDA_VISIBLE_DEVICES=0
  comet-conceptnet:
    environment:
      - CUDA_VISIBLE_DEVICES=0
version: '3.7'
