services:
  agent:
    build:
      context: agent
    container_name: agent
    depends_on:
      - mongo
    ports:
      - 4242:4242
    tty: true
    command: python -m deeppavlov_agent.run -ch http_client --cors
#  spelling-preprocessing:
#    env_file: [.env]
#    build:
#      context: ./annotators/spelling_preprocessing/
#    command: flask run -h 0.0.0.0 -p 3001
#    ports:
#      - 3001:3001
#    environment:
#      - FLASK_APP=server
#    deploy:
#      resources:
#        limits:
#          memory: 50M
#        reservations:
#          memory: 50M
  harvesters_maintenance_skill:
    build:
      context: skills/harvesters_maintenance_skill
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3002
    ports:
      - 3002:3002
  mongo:
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  rule_based_response_selector:
    build:
      context: selectors/rule_based_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3003
    ports:
      - 3003:3003
  emotion_classification:
    build:
      context: annotators/emotion_classification
    command: python -m deeppavlov riseapi emo_bert.json -p 3004
    ports:
      - 3004:3004
  program_y:
    build:
      context: skills/program_y
    ports:
      - 3005:3005
  intent_catcher:
    build:
      context: ./annotators/intent_catcher/
    ports:
      - 3007:3007
    command: python -m deeppavlov riseapi intent_catcher -d -p 3007
version: "3.7"
