services:
  agent:
    volumes:
      - "./assistant_dists/deepy_gobot_base:/dp-agent"
  spelling_preprocessing:
    build:
      context: annotators/spelling_preprocessing
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3881 --timeout=100
    ports:
      - 3881:3881
  harvesters_maintenance_gobot_skill:
    build:
      context: skills/harvesters_maintenance_gobot_skill_deepy
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3882 --timeout=1000
    ports:
      - 3882:3882
  rule_based_response_selector:
    build:
      context: response_selectors/rule_based_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3883
    volumes: []
    ports:
      - 3883:3883
  emotion_classification:
    build:
      context: annotators/emotion_classification_deepy
    command: python -m deeppavlov riseapi emo_bert.json -p 3884
    ports:
      - 3884:3884
  program_y:
    build:
      context: skills/program_y_deepy
    ports:
      - 3885:3885
version: "3.7"
