services:
  agent:
    volumes:
      - "./assistant_dists/deepy_base:/dp-agent"
  spelling_preprocessing:
    build:
      context: annotators/spelling_preprocessing
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3661 --timeout=100
    ports:
      - 3661:3661
  harvesters_maintenance_skill:
    build:
      context: skills/harvesters_maintenance_skill_deepy
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3662
    volumes: []
    ports:
      - 3662:3662
  rule_based_response_selector:
    build:
      context: response_selectors/rule_based_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3663
    volumes: []
    ports:
      - 3663:3663
  emotion_classification:
    build:
      context: annotators/emotion_classification_deepy
    command: python -m deeppavlov riseapi emo_bert.json -p 3664
    ports:
      - 3664:3664
  program_y:
    build:
      context: skills/program_y_deepy
    ports:
      - 3665:3665
version: "3.7"
