version: "3"
   
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
     
  web:
    build: .
    container_name: db_bot
    command:
        - bash
        - ./docker/django-dev.sh
        - ./docker/django-dev.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
    depends_on:
      - db
  tg_bot:
    restart: unless-stopped
    build: .
    command:
      - bash
      - ./docker/bot.sh
    volumes:
      - .:/code
    depends_on:
      - db
      - web