services:
  agent:
    volumes:
      - "./assistant_dists/deepy_adv:/dp-agent"
  spelling_preprocessing:
    build:
      context: annotators/spelling_preprocessing
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3551 --timeout=100
    ports:
      - 3551:3551
  harvesters_maintenance_gobot_skill:
    build:
      context: skills/harvesters_maintenance_gobot_skill_deepy
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3552 --timeout=1000
    ports:
      - 3552:3552
  rule_based_response_selector:
    build:
      context: response_selectors/rule_based_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3553
    volumes: []
    ports:
      - 3553:3553
  emotion_classification:
    build:
      context: annotators/emotion_classification_deepy
    command: python -m deeppavlov riseapi emo_bert.json -p 3554
    ports:
      - 3554:3554
  program_y:
    build:
      context: skills/program_y_deepy
    ports:
      - 3555:3555
  entity_linking:
    build:
      args:
        CONFIG: entity_linking_deepy.json
        PORT: 3556
        SRC_DIR: annotators/entity_linking_deepy
      context: ./
      dockerfile: annotators/entity_linking_deepy/Dockerfile
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 3556:3556
    environment:
      - CUDA_VISIBLE_DEVICES=''
  intent_catcher:
    build:
      context: ./annotators/intent_catcher_deepy/
    ports:
      - 3557:3557
    command: gunicorn --workers=1 --name=catcher --bind 0.0.0.0:3887 --timeout=100 server:app
  sentseg:
    build:
      context: ./annotators/SentSeg/
    command: flask run -h 0.0.0.0 -p 3558
    environment:
      - FLASK_APP=server
    ports:
      - 3558:3558
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1.5G
version: "3.7"
