services:
  sentseg:
    build:
      context: ../../annotators/SentSeg/
    command: bash -c "./setup.sh && gunicorn --workers=1 server:app -b 0.0.0.0:8011 -t 100"
    volumes: []
    ports:
    - 8011:8011
  toxic_classification:
    build:
      args:
        skill_endpoint: toxicity_annotations
        skillconfig: annotators/DeepPavlovToxicClassification/toxic_classification.json
        skillhost: 0.0.0.0
        skillport: 8013
        skilldir: annotators/DeepPavlovToxicClassification/
      context: ../../
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0
    runtime: nvidia
    ports:
    - 8013:8013
  sentiment_classification:
    build:
      args:
        skill_endpoint: sentiment_annotations
        skillconfig: annotators/DeepPavlovSentimentClassification/sentiment_sst_conv_bert.json
        skillhost: 0.0.0.0
        skillport: 8024
        skilldir: annotators/DeepPavlovSentimentClassification/
      context: ../../
      dockerfile: dp/dockerfile_skill_gpu
    environment:
      - CUDA_VISIBLE_DEVICES=0
    runtime: nvidia
    ports:
    - 8024:8024
  sentrewrite:
    build:
      context: ../../annotators/SentRewrite/
    command: bash -c "./setup.sh && gunicorn --workers=1 server:app -b 0.0.0.0:8017 -t 60"
    ports:
    - 8017:8017
  ner:
    build:
      context: ../../annotators/NER/
    environment:
      DEVICE: cuda
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8021 -t 100
    volumes: []
    tty: true
    ports:
    - 8021:8021
  comet_atomic:
    build:
      context: ../../annotators/COMeT/
      args:
        GRAPH: atomic
        PRETRAINED_MODEL: http://lnsigo.mipt.ru/export/alexaprize_data/comet/atomic_pretrained_model.pickle
        PREPROCESS_DATA: http://lnsigo.mipt.ru/export/alexaprize_data/comet/categories_oEffect%23oReact%23oWant%23xAttr%23xEffect%23xIntent%23xNeed%23xReact%23xWant-maxe1_17-maxe2_35-maxr_1.pickle
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8053
    volumes: []
    environment:
        DEVICE: gpu_0
    runtime: nvidia
    ports:
      - 8053:8053
  weather_skill:
    build:
      context: ../../skills/weather_skill/
    command: gunicorn --workers=4 server:app -b 0.0.0.0:8037
    volumes: []
    ports:
      - 8037:8037
version: '2.4'
