services:
  agent:
    volumes:
      - "./assistant_dists/deepy_faq:/dp-agent"
  spelling_preprocessing:
    build:
      context: annotators/spelling_preprocessing
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3771 --timeout=100
    ports:
      - 3771:3771
  faq_skill:
    build:
      context: skills/faq_skill_deepy
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3710 --timeout=1000
    ports:
      - 3710:3710
  rule_based_response_selector:
    build:
      context: response_selectors/rule_based_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3773
    volumes: []
    ports:
      - 3773:3773
  emotion_classification:
    build:
      context: annotators/emotion_classification_deepy
    command: python -m deeppavlov riseapi emo_bert.json -p 3774
    ports:
      - 3774:3774
  program_y:
    build:
      context: skills/program_y_deepy
    ports:
      - 3775:3775
version: "3.7"
